src/renderer/src/components/Modules/Compiler.ts

Почему-то не срабатывало приведение типов через as Blob.

Исправлен баг с сохранением результатов компиляции

---

src/main/index.ts
src/main/modules/ModuleManager.ts
src/preload/index.d.ts
src/preload/index.ts
src/renderer/src/components/Loader.tsx

Чтобы не обращаться к локльному модулю через литералы.

Перенос названия локального модуля загрузчика из main в renderer через window.api

---

src/renderer/src/components/ComponentAddModal.tsx
src/renderer/src/components/Explorer.tsx
src/renderer/src/lib/drawable/Picto.ts
src/renderer/src/lib/utils.ts

В css сделано с помощью object-fit свойства а на канвасе своя функция которая делает тоже самое.

fit icons to containers

---

.eslintrc.json
.prettierrc
src/main/index.ts
src/renderer/src/lib/data/PlatformManager.tsx
src/renderer/src/lib/drawable/Picto.tsx

- Убраны жалобы линтера на CR (endOfLine переведён в auto)
- Фикс перехвата Ctrl-W (он больше не глобальный)
- Добавлен недостающий класс в getMarkedSvg (не соблюдалось соотношение сторон)

Пачка фиксов

---

src/renderer/src/components/Sidebar/Explorer.tsx
src/renderer/src/lib/data/PlatformManager.tsx
src/renderer/src/lib/drawable/Picto.tsx

В прошлый раз иконки не были пофикшены. На картинках хорошо видно у Сенсор и ОружиеМассовое. Не работало потому что у svg нету свойства object-fit, оно только для картинок img. Поэтому сделал так что вместо свгшки возвращается див с абсолютно позиционированным параграфом(label).
**Было:**
**Стало:**

Ещё один фикс иконок

---

src/renderer/src/lib/basic/Container.ts
src/renderer/src/lib/basic/Mouse.ts
src/renderer/src/lib/common/BaseEventEmitter.ts
src/renderer/src/lib/common/EventEmitter.ts
src/renderer/src/lib/common/MouseEventEmitter.ts

Просто типизация для MouseEventEmitter. Для этого вынес базовый класс BaseEventEmitter, в котором можно переопределять метод emit

typed mouse event emitter

---

src/renderer/src/components/CreateModal.tsx
src/renderer/src/components/DiagramEditor.tsx
src/renderer/src/components/EventsModal/EventsModal.tsx
src/renderer/src/lib/data/StatesController.ts
src/renderer/src/utils/index.ts

Что сделано:
- EventsModal отцепился от состояния, раньше EventsModal принимал состояние (state) и сам из него вытаскивал данные с помощью eventSelection. Но так не получается редактировать события в переходе. Теперь EventsModal принимает сам объект события (event) и флаг isEditingEvent. То есть теперь модалке без разницы кто владеет событием
- В DiagramEditor усложнилась логика работы с редактированием событий, приходится хранить и использовать eventsModalParentData если у события есть родитель. В противном случае просто класть или редактировать событие в промежуточном состоянии events
- Добавлена возможность редактирования событий при редактировании состояния или перехода по двойному клику
- defaultTransColor перенесён в utils. Eslint ругался что экспорт чего-то другого вместе с …

Редактирование действий через список в меню события

---

src/renderer/src/components/Sidebar/Compiler.tsx

Кнопка 'Переподключиться' была заблокирована при отсутствии схемы для компиляции, теперь можно переподключиться без предварительного открытия схемы.

Исправление блокировки кнопки переподключения

---

src/renderer/src/components/Sidebar/Loader.tsx
src/renderer/src/components/serverSelect/DocSelectModal.tsx
src/renderer/src/components/serverSelect/FlasherSelectModal.tsx
src/renderer/src/components/serverSelect/ServerSelectModal.tsx

- Модальное окно выбора загрузчика показывает текущий тип сервера (локальный или удалённый)
- Модальные окна выбора загрузчика, компилятора и док-сервера сбрасывают ввод пользователя, если тот не нажал на кнопку "подключиться"

Обновление форм с настройками серверов 

---

src/renderer/src/lib/data/EditorManager/EditorManager.ts
src/renderer/src/lib/data/EditorManager/FilesManager.ts

Теперь после сохранения:
- У файла убирается статус «изменён»
- Обновляется фактическое название файла в заголовке

Фикс отслеживания изменений и названия файла

---

src/main/PlatformSeacher.ts
src/main/file-handlers.ts
src/main/index.ts
src/renderer/src/components/FilePropertiesModal.tsx
src/renderer/src/components/Sidebar/Menu.tsx

Добавление кнопки со свойствами схемы в меню.

Кнопка "Свойства"

---

resources/templates/arduino/blinker.graphml
resources/templates/bearloga/autoborder.graphml

Добавление id у переходов в шаблоны

Фикс шаблонов

---

src/renderer/src/hooks/useDiagramContextMenu.ts
src/renderer/src/lib/basic/EditorView.ts
src/renderer/src/lib/data/EditorController/StatesController.ts

Внутри Shape, отлов клика считается по координатам окна, а в функции создания состояния туда передавались мировые координаты. В будущем нужно переделать так чтобы внутри Shape клик считался по мировым
Closes #293

Фикс: Отлов двойного клика

---

src/renderer/src/components/NoteEdit.tsx
src/renderer/src/lib/data/EditorController/NotesController.ts
src/renderer/src/lib/drawable/Note.ts

Проблема была в том что NoteEdit хранил ссылку на заметку при ее редактировании. После удаления заметки из хранилища обьект не удалялся потому что на него есть ссылка в NoteEdit, поэтому NoteEdit думал что заметка все еще существует.
Переделал на хранение id и текста.
Closes #321

Фикс: При отмене редактирования и удалении заметки сыпет ошибки в консоль

---

src/renderer/src/lib/data/EditorController/StatesController.ts
src/renderer/src/lib/data/EditorController/TransitionsController.ts

Если создать переход на самом верхем уровне, а потом присоеденить состояние к которому он относится то при перелинковке перехода, он задублирвется.
Добавил удаление из верхнего уровня при перелинковке

Фикс: Дублирование перехода внутри дерева Children после линковки

---

.vscode/settings.json

Вывовд от загрузчика выглядит вот так при использовании стандартной кодировки 
Были предприняты попытки исправить проблему через код с использованием библиотек iconv-lite и node-iconv, но это не помогло, к тому же это требует установки дополнительных библиотек.
Поэтому было принято решение поменять кодировку терминала на UTF-8 через настройки vscode.

UTF-8 кодировка для терминала vscode на windows

---

src/renderer/src/assets/styles/preload.css
src/renderer/src/components/WhoopsieScreen.tsx

1) Была исправлена прозрачность с 60% на 80% для того, чтобы экран ошибки не был сильно тусклым;
2) Исправлены стили кнопок и стили текста под стандарт IDE;
3) Выделена кнопка "Консоль".
Было: 
Стало:
closes #347

Выделение кнопки "Консоль" и небольшой редизайн экрана ошибки;

---

src/renderer/src/components/ComponentFormFields.tsx

Исправлен баг из-за которого в поле ввода имени компонента, при добавлении пробела (который автоматический заменяется на подчёркивание) позиция курсора перемещалась в конец поля.

Сохранение позиции курсора при изменении имени компонента

---

src/renderer/src/components/PropertiesModal/PropertiesModal.tsx

Является решение этой проблемы: https://github.com/kruzhok-team/lapki-client/issues/324, однако данное решение не блокирует кнопку, а динамически добавляет известные параметры (до сохранения схемы это - название платформы, после - все остальные свойства).

Передача известных параметров до сохранения схемы

---

src/renderer/src/components/Modules/Flasher.ts

Желательно использовать функцию `flashingEnd` на клиенте после получения от сервера сообщения об окончании прошивки или о невозможности её начать.

Безопасное окончание процесса прошивки 

---

src/renderer/src/components/Modules/Compiler.ts
src/renderer/src/components/Modules/Websocket/ClientStatus.ts
src/renderer/src/components/Sidebar/Compiler.tsx

При достижении таймаута на клиентской части компилятора, статус соединения менялся на "что пошло не так...", что блокировало кнопку "скомпилировать".
Этот PR меняет поведение при таймауте, теперь статус соединения не меняется, но всплывает ошибка, а также появляется сообщение в поле "Результат компиляции" о таймауте.

Исправление таймаута компилятора

---

src/renderer/src/components/CreateSchemeModal/PlatformSelection.tsx

При отсутствии схемы описания нет и его не должно быть, фраза 'Пока что нет описания' вводит в заблуждение. Лучше если на месте описания ничего не будет написано.

Удаление фразы 'Пока что нет описания' 

---

src/renderer/src/lib/data/GraphmlBuilder.ts
src/renderer/src/lib/data/GraphmlParser.ts

Фикс переключения в текстовый режим при невозможности распарсить схему пиктографическую

---

src/renderer/src/components/Sidebar/StateMachinesTab/StateMachinesList.tsx

При нажатии на машину состояния правой кнопкой мыши триггерятся два действия - запрос на удаление и открытие вкладки со схемой машины состояния. Этот PR, убирает удаление при нажатии на правую кнопку мыши, что позволяет открыть вкладку с машиной состояния.

Снятие удаления МС по нажатию на прав. кн. мыши

---

src/renderer/src/lib/data/Initializer.ts
src/renderer/src/lib/data/ModelController/CanvasController.ts
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/NotesController.ts
src/renderer/src/lib/data/ModelController/StatesController.ts

Суть бага: EdgeHandlers биндился только при инициализации данных, но не когда мы добавляли новые состояния и заметки на диаграмму, из-за этого не создавались переходы. Если же сохранить диаграмму в схеме, а потом заново открыть - то у нас происходит инициализация новых данных и поэтому все работает
close https://github.com/kruzhok-team/lapki-client/issues/488

Фикс биндинга EdgeHandlers, фикс бага с инициализацией псевдосостояний выбора

---

src/renderer/src/components/ComponentEditModal.tsx
src/renderer/src/lib/data/ModelController/CanvasController.ts

1. Не показывалась основная информация о компоненте при редактировании
2. В Берлоге уже добавленные статические компоненты были доступны для добавления

Фикс модального окна для редактирования компонентов, фикс формирования списка доступных компонентов для добавления

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
src/renderer/src/utils/ComponentAttribute.ts

- Теперь все параметры проходят валидацию при отправке формы, а не при каждом изменение ввода, как это было раньше.
- Исправлен баг, когда при вводе символа '.' поле переключалось в режим атрибутов параметров.
- При парсинге параметра, проверяется, записан ли он при помощи символа кавычки `'` (это сделано для того, чтобы подобный текст `'.'` не считался за атрибут.
- При переключении поля в режим выбора атрибутов больше не появляется отступ.
- При отправке параметра как атрибута, проверяется наличие метода (чтобы нельзя было отправить что-то вроде `Counter1.`).
- При провале валидации, текст ошибки отображается не только для обычных полей ввода, но и для селекторов атрибутов-параметров.

Улучшения и исправления парсинга и валидации атрибутов как параметров

---

src/renderer/src/components/Sidebar/Loader.tsx

Если селектор машин состояний и выбранный файл для прошивки присутствуют одновременно, то это может сбить с толку пользователя, ведь ему будет не понятно откуда будет браться прошивка.
Старый вид:
Новый вид:

Скрытие селектора МС при выборе файла

---

src/renderer/src/components/Sidebar/Loader.tsx
src/renderer/src/hooks/useFileOperations.ts

Старые данные комплиятора влияют на работу загрузчика, они препятствует корректной проверки типа платы, из-за чего можно загрузить схему, предназначенную для платформы А на плату типа Б.

Очистка данных компилятора после создания/открытия новой схемы

---

src/renderer/src/components/ComponentFormFieldLabel.tsx
src/renderer/src/components/ComponentFormFields.tsx

Эти дефолтные значения были явно добавлены неумышленно, потому что появлялись они из-за того, что, если параметр отсутствует, он заменяется `пустой строкой`, которая затем кастилась к нулю в селекторе в отрыве от функций, которые прокидывали значение селектора вверх.
```jsx
<Select
className="w-[250px]"
options={options}
value={options.find((o) => o.value === value || o.value === Number(value))}
onChange={({ value }: any) => handleInputChange(name, value)}
/>
```
Теперь при создании компонента пользователя ожидают пустые селекторы, которые только и ждут, чтобы их явно заполнили.
close https://github.com/kruzhok-team/lapki-client/issues/592

Удаление значений по умолчанию в селекторах

---

src/renderer/src/components/Sidebar/Compiler.tsx

close https://github.com/kruzhok-team/lapki-client/issues/622

Удаление лишних запятых при отображении не прошедших компиляцию МС

---

src/renderer/src/components/ManagerMS.tsx

В поле `bootloader REF_HW` отображалось не то значение

Фикс отображения метаданных МС-ТЮК

---

src/renderer/src/lib/drawable/TransitionNode/ArrowsWithLabel.ts
src/renderer/src/lib/drawable/TransitionNode/ArrowsWithoutLabel.ts
src/renderer/src/lib/styles.ts

- Opacity добавлено в transitionStyles
- Теперь opacity применяется для стрелок из начального состояния
- Стрелки стали шире

Изменение стиля стрелок

---

src/renderer/src/components/Sidebar/Setting.tsx

Увеличение отступа от заголовка темы до селектора

---

src/renderer/src/components/Sidebar/Flasher/FlasherTable.tsx

Раньше при проверке доступных для загрузки в плату МС-ТЮК схем, версия для платы игнорировалась. Например, схемы для плат `tjc-ms1-mtrx-a2` и `tjc-ms1-mtrx-a3` считались одинаковыми. Теперь же в плату `tjc-ms1-mtrx-a2` нельзя загрузить схему типа `tjc-ms1-mtrx-a3`.

Строгая проверка на соответствие типа и версии

---

src/renderer/src/hooks/useFlasherHooks.ts

Если подключить две центральный платы (через USB), а затем отключить одну из них, то может возникнуть ситуация, когда IDE терял ID той центральной платы, через которую нужно загружать прошивки.

Загрузчик: исправление бага с потерей ID центральной платы МС-ТЮК

---

src/renderer/src/hooks/useFlasherHooks.ts

Если у платы не было указано имени в IDE, то названия вкладки с отчётом выглядело следующим образом " - МС-ТЮК (COM4)", теперь же названия будет выглядеть так "668e739880610dc1 - МС-ТЮК (COM4)", где первая часть - это адрес платы.
close #857

Исправление наименования вкладок с отчётами прошивок для МС-ТЮК

---

src/renderer/src/components/MainContainer/Tabs/Tabs.tsx
src/renderer/src/hooks/useFileOperations.ts
src/renderer/src/lib/data/EditorModel/FilesManager.ts
src/renderer/src/store/useTabs.ts

При смене активной вкладки, не учитывалось содержит ли вкладка холст или нет, из-за этого не менялся ID текущего контроллера (headControllerId). 
Это приводило к тому, что при создании документа сразу с несколькими МС, отрывалась вкладка с холстом первой по порядку МС, но при этом список компонетнов и иерархия принадлежали последней МС.

Исправление смены активной вкладки

---

src/renderer/src/components/ComponentEditModal.tsx
src/renderer/src/components/ComponentFormFieldLabel.tsx
src/renderer/src/components/ComponentFormFields.tsx

- Исправлена проблема, что сброс ошибки при изменении значения работал только для текстового поля. 
- Исправлено сохранение ошибки об отсутствии параметра в структуре errors.
- Исправлено отсутствие сообщения об ошибке, если в ComponentFormFieldLabel есть вложенные компоненты.

Фикс проверки обязательных параметров

---

src/renderer/src/components/Sidebar/Flasher/SerialMonitor.tsx

На актуальной версии IDE, при открытии вкладки с монитором порта, всегда появляется сообщение: 'Перевод в режим Текст/HEX'. Это происходило из-за хука, привязанного к настройке режима монитора. Он здесь не нужен. Вместо него, необходимые действия происходит непосредственно при смене настроек.

Рефакторинг монитора порта + Удаление лишнего сообщения о режиме монитора при его открытии

---

src/renderer/src/components/Sidebar/Flasher/SerialMonitor.tsx

- Исправление бага из-за которого в сообщение о смене режима монитора порта указывалось старое название режима, а не новое (например, "Перевод в режим Текст", вместо "Перевод в режим HEX")
- Если пользователь в селекторе выберет текущий режим, то это действие проигнорируется (например, выбор режима "Текст", когда монитор порта уже находится в этом режиме)

Хот-фиксы для монитора порта
