src/renderer/src/App.tsx
src/renderer/src/lib/data/EditorManager.ts

Отображение платформы в названии

---

src/renderer/src/App.tsx
src/renderer/src/components/ComponentAddModal.tsx
src/renderer/src/components/ComponentDeleteModal.tsx
src/renderer/src/components/ComponentEditModal.tsx
src/renderer/src/components/Explorer.tsx
src/renderer/src/components/Sidebar/Sidebar.tsx
src/renderer/src/hooks/useAddComponent.ts
src/renderer/src/hooks/useDeleteComponent.ts
src/renderer/src/hooks/useEditComponent.ts

Вынес логику модалок связанных с компонентами в хуки, НУЖНО ТЕСТИРОВАТЬ, я всех кейсов которые были предусмотрены не знал.

refactor component modals

---

src/renderer/src/hooks/useEditComponent.ts
src/renderer/src/lib/data/StateMachine.ts
src/renderer/src/lib/drawable/State.ts

Поправил две небольшие опечатки. Не пробрасывались данные компонентов и не удалялись переходы.

fix mistypos

---

src/renderer/src/components/ComponentEditModal.tsx
src/renderer/src/lib/data/EditorManager.ts

- В редакторе компонентов не обновляется форма с параметрами компонента.
- Созданные переходы не пробросились в данные и не сохранились в файл.

fix transitions save and components edit form

---

src/renderer/src/hooks/useDiagramContextMenu.ts
src/renderer/src/lib/data/StateMachine.ts
src/renderer/src/lib/drawable/States.ts
src/renderer/src/lib/drawable/Transitions.ts

Теперь копировать связи стало возможным, для этого выберите связь в редакторе машины состояний и нажмите сочетание клавиш "ctrl+C", а затем нажмите "ctrl+V".

Реализовано глобальное копирование связей.

---

.eslintrc.json
.vscode/settings.json

return eslint

---

src/renderer/src/components/Loader.tsx
src/renderer/src/components/Modules/Flasher.ts

Во время подключения к удалённому хосту появляется кнопка "отменить", которая отменяет попытку подключиться, после нажатия на неё, клиент не будет пытаться автоматически подключаться к хосту.

Кнопка отмены подключения для загрузчика

---

src/main/index.ts
src/renderer/src/components/DiagramEditor.tsx
src/renderer/src/components/StateNameModal.tsx

1) Была устранена вечная ошибка при первом переименовании состояния;
2) Теперь при прокрутке колеса мышки, окно переименования состояния будет исчезать;
3) Исправлен баг с сочетанием клавиш в electron(теперь быстрая перезагрузка "Ctrl+R" и другие сочетания вновь работают);
4) Глобально убрано событие electron "Ctrl+W", теперь он не будет экстренно закрываться.
Требуется срочное добавление в главный проект в связи с устранением небольших, но важных багов.

Исправление багов.

---

.eslintrc.json
.vscode/settings.json
src/renderer/src/components/MainContainer.tsx

Eslint fixes

---

.github/workflows/typecheck.yml

Пока запускает typecheck. Потом можно отдельно положить prettier+eslint с автозаписью.

Пробный конвейер для проверки типов

---

src/renderer/src/lib/basic/Container.ts

Фикс центрирования камеры при отсутсвии нод

fix camera centering

---

src/renderer/src/components/Menu.tsx
src/renderer/src/lib/data/EditorManager.ts

Кнопка открыть файл не работала и при открытии новой схемы не обновлялся список компонентов

fix open file function, fix components update after new file open

---

src/renderer/src/lib/drawable/BaseTransition.ts
src/renderer/src/lib/drawable/Condition.ts
src/renderer/src/lib/drawable/Picto.tsx
src/renderer/src/lib/utils.ts

Скругление углов

---

src/renderer/src/lib/data/StateMachine.ts

Центрирования камеры после открытия схемы

---

src/renderer/src/lib/data/StateMachine.ts

Перерасчёт высоты состояния при любых изменениях событий

state height recalculation fix

---

package-lock.json
package.json
src/renderer/src/lib/basic/Canvas.ts

Добавил задержку на событие ресайза для холста. Теперь при ресайзе ничего не дёргается

add debounce to canvas resize event

---

src/renderer/src/lib/basic/Container.ts
src/renderer/src/lib/data/DrawList.ts
src/renderer/src/lib/data/StateMachine.ts
src/renderer/src/lib/drawable/States.ts
src/renderer/src/lib/drawable/Transitions.ts

Closes #61
Тут просто добавлен DrawList, на основе которого происходит рендер

Очередь рендера

---

src/renderer/src/lib/basic/Container.ts
src/renderer/src/lib/data/MachineController.ts
src/renderer/src/lib/drawable/Children.ts

В общем тут пока костыльно, с этими parent и children ситуация напряжённая, рефактор будет во время добавления возможности нескольких машин состояний.
Пофиксил ещё Issue #73

fix, link and unlink transition with states

---

src/renderer/src/components/Sidebar/Menus.tsx

add ability to scroll in sidebar

---

src/renderer/src/lib/data/MachineController.ts
src/renderer/src/lib/data/StatesController.ts
src/renderer/src/lib/data/UndoRedo.ts
src/renderer/src/lib/drawable/Children.ts
src/renderer/src/types/MachineController.ts

Фикс того что при удалении вложенного состояния удалялись и переходы родителя

Фикс: при удалении вложенного состояния удалялись переходы родителя

---

src/renderer/src/hooks/useDiagramContextMenu.ts
src/renderer/src/lib/CanvasEditor.ts
src/renderer/src/lib/basic/Container.ts
src/renderer/src/lib/basic/Keyboard.ts
src/renderer/src/lib/basic/Mouse.ts
src/renderer/src/lib/common/BubbleEventEmitter.ts
src/renderer/src/lib/data/EditorManager.ts
src/renderer/src/lib/data/MachineController.ts
src/renderer/src/lib/data/StatesController.ts
src/renderer/src/lib/data/TransitionsController.ts
src/renderer/src/lib/drawable/EdgeHandlers.ts
src/renderer/src/lib/drawable/Node.ts
src/renderer/src/types/mouse.ts

Closes #80
- Привёл поведение в соответствие со связанным тикетом.
- Добавил реакцию на правую кнопку, левые Shift и Ctrl.
- Пофиксил вкладывание состояний.
- Обобщил эммитер событий для мыши, связанные типы вынес в отдельный модуль.
- Убрал лишнюю прослойку (handle-функции).
- Добавил недостающую функцию очистки событий для мыши.

Переработка поведения мыши и клавиатуры 

---

src/renderer/src/components/Sidebar/Loader.tsx

Closes #79 Сделал кнопку растягиваемой

Фикс кнопки на вкладке загрузчика

---

src/renderer/src/components/PlatformSelectModal.tsx

Изменил PlatformSelectModal. Убрал ошибочку из-за того что не было key, плюс рефакторинг вёрстки

Рефакторинг модалки выбора платформы

---

demos/child-before-parent.json
src/renderer/src/lib/data/MachineController/Initializer.ts
src/renderer/src/lib/data/MachineController/MachineController.ts
src/renderer/src/lib/data/MachineController/index.ts

Это рефакторинг и фикс бага. Баг заключался в том что состояния не правильно инициализировались если сначала создавались дети а потом родители (не линковались). 
Добавил схему с таким вариантом(child-before-parent.json). 
Плюс вынес инициализацию в отдельный класс Initializer, думаю из MachineController стоит многое вынести в отдельные классы (но это на будущее)

Fix machine controller initialization

---

.github/workflows/tagged-release.yml

Сделал workflow для создания автоматического релиза Closes #4 
- Работает на тег который начинается на v, например, v0.0.1
- Внутрь релиза записываются все коммиты начиная с прошлого тега
- Также внутрь релиза попадают сбилженные файлы под линукс и виндовс
- Для билда используется специальный docker image в котором есть все зависимости (оказалось что сбилдить под виндовс на линуксе не так просто)

Автоматический релиз

---

src/renderer/src/assets/icons/add.svg
src/renderer/src/assets/icons/subtract.svg
src/renderer/src/components/ComponentFormFields.tsx
src/renderer/src/components/CreateModal.tsx
src/renderer/src/components/EventsModal.tsx
src/renderer/src/components/Modal/ColorInput.tsx
src/renderer/src/components/Modal/TextInput.tsx
src/renderer/src/components/serverSelect/FlasherSelectModal.tsx
src/renderer/src/index.css

Переделал всё что было с константных цветов на те что в теме
Closes #96

Фикс светлой темы

---

package-lock.json
package.json
src/renderer/src/components/Modules/Compiler.ts
src/renderer/src/components/Modules/Flasher.ts

Фикс маленькой ошибки, из-за которой не отправлись данные на компилятор
Также поставил @types/ws, чтобы показывались типы и функции у вебсокета. Но из-за этого выявилось много несостыковок по типам в модулях Flasher и Compiler. Компилятор я пофиксил, Flasher трогать не стал, так как нет возможности оттестить изменения.

Фикс ошибки с отправкой данных на компилятор

---

src/renderer/src/components/Modules/Compiler.ts
src/renderer/src/components/Sidebar/Compiler.tsx

https://github.com/kruzhok-team/lapki-client/issues/110

Исправление бага из-за которого кнопка "скомпилировать" разблокируется при подключении, если открыта схема

---

.github/workflows/tagged-release.yml

Сделал подгрузку avrdude для windows. То есть до билда в папку resources/modules/win32 докачиваются 3 файла (avrdude.conf avrdude.exe avrdude.pdb)
Closes #113

Подгрузка avrdude для windows

---

src/renderer/src/components/Sidebar/Compiler.tsx
src/renderer/src/components/Sidebar/Loader.tsx
src/renderer/src/components/Sidebar/Sidebar.tsx
src/renderer/src/hooks/useDiagramContextMenu.ts
src/renderer/src/hooks/useFileOperations.ts
src/renderer/src/lib/basic/Container.ts
src/renderer/src/lib/data/EditorManager/EditorManager.test.ts
src/renderer/src/lib/data/EditorManager/EditorManager.ts
src/renderer/src/lib/data/EditorManager/FilesManager.ts
src/renderer/src/lib/data/EditorManager/Serializer.ts
src/renderer/src/lib/data/EditorManager/index.ts
src/renderer/src/lib/data/MachineController/Initializer.ts
src/renderer/src/lib/data/StatesController.ts

Пофиксил баг из issue #117 (не чистились события InitialStateMark)
Отрефакторил EditorManager:
- Вынес классы FilesManager и Serializer
- Изменил прокси на ручной триггер изменения данных
Closes #111 
Closes #117

EditorManager рефакторинг, фикс InitialState

---

package-lock.json
src/main/index.ts
src/renderer/src/components/AboutTheProgramModal.tsx

Доработал диалог «О программе», а именно сделал так, чтобы не приходилось менять версию в нескольких точках. Заодно вынес изменчивые вещи в константы.

Получение версии приложения из пакета

---

resources/platform/ArduinoMicro.json
src/renderer/src/components/Modules/Compiler.ts

Добавлена платформа ArduinoMicro, компиляция с флагом _-b arduino:avr:micro_

Поддержка Arduino Micro

---

demos/CyberiadaSchemas/CyberiadaFormat-Blinker.graphml

Исправил опечатку во втором состоянии.

Фикс примера Blinker

---

src/renderer/src/components/EventsModal.tsx

Добавил сброс в эффекте
Closes #132

Не обновляется выпадающий список в редакторе действия

---

src/renderer/src/components/UI/Select/style.css

Неправильный скролл в селекте

---

src/renderer/src/lib/data/TransitionsController.ts

Добавил обновление холста после очистки призрачного перехода
Closes #164

Баг создания перехода

---

package-lock.json
package.json
src/main/checkForUpdates.ts
src/main/index.ts
src/renderer/src/App.tsx
src/renderer/src/components/UpdateModal.tsx
src/renderer/src/components/index.ts
src/renderer/src/hooks/useModal.ts

Что изменилось:
- Добавил функцию checkForUpdates, она принимает текущую версию программы из package.json и сравнивает её с версией из последнего релиза, функция использует каррирование.
- Добавил маленький пакетик compare-versions https://bundlephobia.com/package/compare-versions@6.1.0 По сравнению со стандартным semver он вообще малютка
- В хуке useModal обернул функции в useCallback для уменьшения количества перерисовок
- Добавил компонент UpdateModal который отвечает сам за себя, когда открыть, когда закрыть, что показать

Проверка обновлений

---

demos/CyberiadaSchemas/CyberiadaFormat-Autoborder.graphml
resources/templates/bearloga/autoborder.graphml
src/renderer/src/components/CreateModal/CreateModal.tsx
src/renderer/src/components/UI/Select/Select.tsx
src/renderer/src/lib/basic/Container.ts
src/renderer/src/lib/data/GraphmlParser.ts
src/renderer/src/lib/data/MachineController/MachineController.ts

- Для Берлоги не сохранялись параметры переходов. Пофиксил и обновил примеры.
- Добавлен горизонтальный скролл (для тачпадов)
- Условия в редакторе связи прогружались неполностью. Пофиксил. 
- Можно было сохранить недописанное условие (без оператора или метода). Пофиксил критичную часть.
- Добавил русскоязычную подсказку в выпадающее меню (но уж часто её видно).

Мелкие фиксы (скролл и сохранение Берлоги)

---

package-lock.json
package.json
src/renderer/src/assets/icons/check.svg
src/renderer/src/components/CreateModal/Condition.tsx
src/renderer/src/components/CreateModal/CreateModal.tsx
src/renderer/src/components/CreateModal/EventsBlockModal.tsx
src/renderer/src/components/UI/Checkbox.tsx
src/renderer/src/components/UI/ColorInput.tsx
src/renderer/src/components/UI/Select/Select.tsx
src/renderer/src/components/UI/Switch.tsx
src/renderer/src/components/UI/TextInput.tsx
src/renderer/src/components/UI/index.ts
src/renderer/src/components/serverSelect/DocSelectModal.tsx
src/renderer/src/components/serverSelect/FlasherSelectModal.tsx
src/renderer/src/components/serverSelect/ServerSelectModal.tsx
src/renderer/src/hooks/index.ts
src/renderer/src/hooks/useCreateModalCondition.tsx

- Вынес компонент Condition
- Добавил ошибки в условие связи
- Убрал стандартные поля ввода

Компонент Condition

---

src/renderer/src/lib/data/PlatformManager.tsx
src/renderer/src/lib/drawable/Picto.tsx

Оказывается, roundRect – это не атомарная операция, а часть пути. Читайте документацию, потомки.

Фикс отрисовки пиктограмм условия

---

src/renderer/src/components/UI/TextInput.tsx
src/renderer/src/components/serverSelect/DocSelectModal.tsx
src/renderer/src/components/serverSelect/FlasherSelectModal.tsx
src/renderer/src/components/serverSelect/ServerSelectModal.tsx

Исправлена ошибка с textInput, теперь элемент не слипается.

---

src/renderer/src/hooks/useErrorModal.tsx

Добавил принудительный перенос
Closes #190

Длинные пути файлов

---

src/renderer/src/components/Documentation/Documentation.tsx

Документация под данный функционал тоже заменилась.

В клиенте добавлены кнопки "назад" и "вперёд" для быстрого переключения между страницами.

---

demos/CyberiadaSchemas/CyberiadaFormat-Blinker.graphml
src/renderer/src/lib/data/EditorManager/Serializer.ts
src/renderer/src/lib/data/GraphmlParser.ts

Сделано:
- обработка при импорте
- обработка при экспорте

Обработка заметок в GraphmlParser

---

src/renderer/src/assets/icons/arrow-right.svg
src/renderer/src/components/Documentation/Documentation.tsx
src/renderer/src/components/Documentation/components/Directory.tsx
src/renderer/src/components/Documentation/components/Navigation.tsx
src/renderer/src/components/Documentation/components/Tree.tsx

Доработка переключения страниц документации

---

src/renderer/src/components/NoteEdit.tsx
src/renderer/src/lib/data/EditorManager/Serializer.ts
src/renderer/src/lib/data/MachineController/MachineController.ts
src/renderer/src/lib/data/NotesController.ts
src/renderer/src/lib/drawable/Note.ts

Добавил выделение, плюс небольшой рефакторинг функций выделения и получения стилей заметки
Closes #220

Выделение заметок

---

package-lock.json
package.json
src/renderer/src/components/CodeEditor.tsx
src/renderer/src/components/Sidebar/Compiler.tsx
src/renderer/src/types/tabs.ts
src/renderer/src/utils/index.ts

Подсветка синтаксиса исходного кода в зависимости от расширения файла

---

src/renderer/src/components/DiagramContextMenu.tsx
src/renderer/src/components/Documentation/Documentation.tsx
src/renderer/src/components/Documentation/components/Show.tsx
src/renderer/src/components/Documentation/components/Tree.tsx
src/renderer/src/hooks/index.ts
src/renderer/src/hooks/useFetch.ts

Что сделано:
- Изменение подгрузки документации на кстомный хук (useFetch)
- Каждая страничка документации стала подгружать сама себя
- Отображение ошибок с возможностью перезагрузить
Closes #188

Изменение подгрузки документации

---

package-lock.json
src/renderer/src/components/DiagramEditor.tsx
src/renderer/src/components/MainContainer/MainContainer.tsx

Переместил компонент с кнопками зума в правильное место
Closes #240

Увеличение/уменьшение зума на холсте, когда открыта вкладка с файлами

---

src/renderer/src/lib/data/ElementsValidator.ts

Исправление багов валидации

---

src/renderer/src/components/DiagramContextMenu.tsx

floating-ui выдавал ошибку что в reference элемент нельзя передавать виртуальный элемент. Работало и с ошибкой но возможно в новых версиях перестанет, сделал как советуют в документации

Ошибка floating-ui

---

src/renderer/src/hooks/useFileOperations.ts

fix scheme creation from template

---

src/renderer/src/components/DiagramEditor.tsx
src/renderer/src/lib/data/EditorController/TransitionsController.ts

Создание перехода в конечное состояние через модальное окно

Создание перехода в конечное состояние через модальное окно

---

src/renderer/src/components/CreateModal/CreateModal.tsx

Баг CreateModal ломающий IDE

---

src/renderer/src/components/CreateModal/CreateModal.tsx
src/renderer/src/components/CreateModal/hooks/useCondition.tsx
src/renderer/src/components/CreateModal/hooks/useTrigger.tsx
src/renderer/src/lib/data/EditorModel/EditorModel.ts
src/renderer/src/lib/data/History.ts
src/renderer/src/lib/drawable/Node/ChoiceState.ts
src/renderer/src/lib/utils/index.ts

Фиксы из комментариев #269 
Плюс исправление бага #296 
Closes #296

Фиксы модального окна нод

---

src/renderer/src/components/CreateModal/EventsBlock.tsx
src/renderer/src/components/CreateModal/hooks/useCondition.tsx
src/renderer/src/components/CreateModal/hooks/useTrigger.tsx
src/renderer/src/components/EventsModal/EventsModal.tsx
src/renderer/src/components/MainContainer/MainContainer.tsx
src/renderer/src/components/Sidebar/Explorer/ComponentsList.tsx
src/renderer/src/hooks/useComponents.ts
src/renderer/src/hooks/useErrorModal.tsx
src/renderer/src/lib/CanvasEditor.ts
src/renderer/src/lib/data/EditorController/EditorController.ts
src/renderer/src/lib/data/EditorController/Initializer.ts
src/renderer/src/lib/data/EditorModel/EditorModel.test.ts
src/renderer/src/lib/data/EditorModel/EditorModel.ts
src/renderer/src/lib/drawable/Events.ts
src/renderer/src/lib/drawable/Transition.ts

Платформа сделана опциональной так как она подгружается асинхронно

Опциональная платформа

---

src/renderer/src/lib/data/History.ts

При обрезании стека истории стали учитываться группы элементов

Фикс: Обрезание стека истории при привышении лимита учитывая группировку элементов

---

.vscode/settings.json

Reverts kruzhok-team/lapki-client#325

Revert "UTF-8 кодировка для терминала vscode на windows"

---

src/renderer/src/lib/data/EditorController/EditorController.ts
src/renderer/src/lib/data/EditorController/Initializer.ts
src/renderer/src/lib/data/PlatformManager.tsx

Проблема - икноки компонентов подгружаются не сразу
Решение - инициализация иконок сразу после загрузки платформы

Подгрузка иконок компонентов

---

src/renderer/src/components/Sidebar/Menu.tsx

Можно использовать кнопку "сохранить как" сколько угодно раз (если схема инициализирована).

Кнопка "сохранить как" не требует наличия изменений

---

src/renderer/src/components/ComponentAddModal.tsx
src/renderer/src/components/ComponentDeleteModal.tsx
src/renderer/src/components/ComponentEditModal.tsx
src/renderer/src/components/DiagramContextMenu.tsx
src/renderer/src/hooks/useComponents.ts
src/renderer/src/hooks/useDiagramContextMenu.ts
src/renderer/src/lib/CanvasEditor.ts

Реализация фокуса на редактор при нажатии пункта в контекстном меню и при закрытии модальных окон в компонентах.

---

src/renderer/src/components/Sidebar/History.tsx

Первый вариант:
Второй вариант:
closes #272

Переименование заголовков в разделе истории изменений.

---

src/renderer/src/lib/data/EditorController/TransitionsController.ts

Добавлен запрет на удаление связи у начального состояния.

---

src/renderer/src/components/ComponentFormFields.tsx

Является решением этой проблемы: https://github.com/kruzhok-team/lapki-client/issues/315

Замена пробелов в названиях компонентов на подчёркивания

---

src/renderer/src/components/Sidebar/Loader.tsx

Условие блокировало загрузку своего собственного файла с прошивкой (кнопка с троеточием) при подключении на удалённый сервер, если на локальном сервере отсутствует avrdude.

Исправление бага с блокировкой загрузки файла с прошивкой при отсутствии avrdude на удалённый сервер

---

src/renderer/src/assets/icons/clone.svg
src/renderer/src/components/DiagramContextMenu.tsx
src/renderer/src/hooks/useDiagramContextMenu.ts
src/renderer/src/lib/data/EditorController/EditorController.ts
src/renderer/src/lib/data/EditorController/StatesController.ts
src/renderer/src/lib/types/EditorController.ts

Добавлен копипаст для псевдосостояния.
И добавлено дублирования для всех требуемых элементов редактора(состояние, псевдосостояние, связь, заметка).
closes #349 
closes #348

Добавлено дублирование в контекстное меню.

---

src/main/index.ts
src/main/modules/ModuleManager.ts
src/main/settings.ts
src/renderer/src/components/Sidebar/Loader.tsx

Получение информации об установке avrdude через ipc и удаление поля hasAvrdude из electron-settings

Получение информации об установке avrdude через ipc

---

src/main/index.ts
src/renderer/src/lib/data/EditorController/EditorController.ts

Фикс бага вставки состояний

---

src/renderer/src/lib/data/GraphmlBuilder.ts

Фикс бага со вставкой неправильного разделителя для статических компонентов в условиях

---

src/main/settings.ts
src/renderer/src/components/SerialMonitor.tsx

https://github.com/kruzhok-team/lapki-client/issues/391

Монитор порта: добавление сохранения настроек

---

src/renderer/src/components/Modules/Flasher.ts
src/renderer/src/components/Modules/SerialMonitor.ts
src/renderer/src/types/FlasherTypes.ts

- Добавление функции send для избавления избыточного кода
- Добавление отдельных типов данных для payload и type в FlasherMessage
- Исправление 'unmarshal-error' на 'unmarshal-err'

Рефактор обработки вебсокет-сообщений через Flasher

---

src/renderer/src/lib/data/GraphmlParser.ts

Сохранение действий статических компонентов

---

src/renderer/src/components/Modules/Flasher.ts
src/renderer/src/components/Sidebar/Loader.tsx

https://github.com/kruzhok-team/lapki-client/issues/403

Автоматическое отключение порта при прошивке

---

src/renderer/src/components/MainContainer/Tabs/Tabs.tsx

https://github.com/kruzhok-team/lapki-client/issues/429

Исправление бага из-за которого кнопка "Посмотреть код" в схемах не показывает код

---

src/renderer/src/components/Hierarchy/TitleRender.tsx

Фикс бага с вылетом IDE при использовании только цифр в названии состояния 

---

src/renderer/src/lib/data/ModelController/CanvasController.ts

https://github.com/kruzhok-team/lapki-client/issues/469

Исправление функции удаления компонента

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx

Суть бага: при закрытии вкладки мы проверяем, является ли следующая активная вкладка редактором МС/схемоэкраном, и если нет, то главным становится призрачный контроллер, что и происходило. После прошлого редактирования действия в ActionsModal сохранилась initialData, из-за чего в ActionsModal вызвалась функция init, где мы пытались достать платформу для призрачной МС  (так как мы работаем с первой попавшейся МС, на которой подписан главный контроллер, которым в момент вызова функции стал призрачный канвас) и достать из нее информацию о компоненте через getComponent. И так как платформы для призрачной МС не существует, то приложение вылетало
close #476

Фикс бага с вылетом IDE при закрытии вкладки с кодом

---

src/renderer/src/components/ComponentAddModal.tsx
src/renderer/src/components/ComponentEditModal.tsx
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/UserInputValidator.ts

Общее пространство имен компонентов при валидации

---

src/renderer/src/lib/data/EditorModel/Serializer.ts
src/renderer/src/lib/data/GraphmlBuilder.ts

Фикс изменения типа матрицы после неудачной компиляции

---

resources/platform/tjc-ms1-mtrx-a2-1.0.json

fix mtrx platform

---

tailwind.config.js

Почему-то в одном из PR, определния этих цветов пропали.
#512

Возвращение стандартных цветов для переходов и состояний

---

src/renderer/src/components/Sidebar/Menu.tsx

Скрытие кнопок при открытом схемоэкране

---

src/renderer/src/lib/basic/Canvas.ts

close https://github.com/kruzhok-team/lapki-client/issues/528

Фикс выделения канваса при фокусе

---

src/renderer/src/components/EditorSettings.tsx

close https://github.com/kruzhok-team/lapki-client/issues/531

Настройки канваса не отображаются на не-канвасах

---

src/renderer/src/lib/data/ModelController/ModelController.ts

close https://github.com/kruzhok-team/lapki-client/issues/527

Удаление переходов, исходящих из псевдосостояния выбора

---

src/renderer/src/lib/data/ModelController/CanvasController.ts

close https://github.com/kruzhok-team/lapki-client/issues/520

Изменение размера состояния после удаления события

---

src/renderer/src/lib/data/GraphmlBuilder.ts

Я не смог воспроизвести проблему, но, думаю, это поможет
close https://github.com/kruzhok-team/lapki-client/issues/546

Фикс добавления скобок к сигналам при экспорте схемы

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx

Фикс вызова ререндера во время рендера другого компонента

---

src/renderer/src/lib/data/ModelController/StatesController.ts

close https://github.com/kruzhok-team/lapki-client/issues/518

Обводка состояний

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModalParameters.tsx
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/StatesController.ts

close https://github.com/kruzhok-team/lapki-client/issues/509

Правильные значения параметров при откате действий

---

src/renderer/src/components/Modules/Compiler.ts
src/renderer/src/components/Sidebar/Compiler.tsx

close https://github.com/kruzhok-team/lapki-client/issues/548

Правильное отображение результата компиляции

---

src/renderer/src/lib/drawable/ComponentNode/Component.ts
src/renderer/src/lib/drawable/Picto.tsx

Фикс масштабирования метки компонента

---

src/renderer/src/components/Modules/Flasher.ts
src/renderer/src/components/Modules/ManagerMS.ts
src/renderer/src/types/FlasherTypes.ts

Отсутствует бинарник для macOS. Обновление для него будет выложен отдельным PR.

Обратная связь загрузчика (МС-ТЮК)

---

src/renderer/src/lib/data/ModelController/ModelController.ts

close https://github.com/kruzhok-team/lapki-client/issues/577

Создание переходов в конечное состояние

---

src/renderer/src/components/ManagerMS.tsx
src/renderer/src/components/Modules/Flasher.ts
src/renderer/src/components/Modules/ManagerMS.ts
src/renderer/src/types/FlasherTypes.ts

Теперь показывается прогресс выпонения этапов загрузки.

Улучшенная обратная связь загрузки МС-ТЮК

---

src/renderer/src/components/ComponentAddModal.tsx
src/renderer/src/components/Sidebar/StateMachinesTab/StateMachinesList.tsx
src/renderer/src/components/StateMachineEditModal.tsx
src/renderer/src/components/UI/Modal/Modal.tsx
src/renderer/src/hooks/useStateMachines.ts
src/renderer/src/lib/data/EditorModel/EditorModel.ts
src/renderer/src/lib/data/ModelController/CanvasController.ts
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/UserInputValidator.ts
src/renderer/src/lib/types/ControllerTypes.ts
src/renderer/src/lib/types/ModelTypes.ts

Дублирование машин состояний, фикс бага с открытием вкладки МС

---

src/renderer/src/components/FirmwareSelectMS1.tsx
src/renderer/src/components/ManagerMS.tsx
src/renderer/src/hooks/useAddressBook.ts
src/renderer/src/types/FlasherTypes.ts

Теперь запоминаются индексы адресов в адресной книге, вместо простого копирования.

Синхронизация выбранных схем и адресов с адресной книгой для загрузки в МС-ТЮК

---

src/renderer/src/components/Hierarchy/Hierarchy.tsx
src/renderer/src/components/Hierarchy/TitleRender.tsx
src/renderer/src/components/Sidebar/Explorer/ComponentsList.tsx
src/renderer/src/components/Sidebar/Explorer/Explorer.tsx
src/renderer/src/components/Sidebar/Explorer/StateMachinesHierarchy.tsx
src/renderer/src/lib/data/ModelController/CanvasController.ts
src/renderer/src/lib/data/ModelController/ModelController.ts

close https://github.com/kruzhok-team/lapki-client/issues/519
(Опечатка исправлена)

Доработка иерархии для работы с несколькими машинами состояний

---

src/renderer/src/components/Hierarchy/Hierarchy.tsx
src/renderer/src/lib/data/ModelController/ModelController.ts

close https://github.com/kruzhok-team/lapki-client/issues/610

Фикс вылета при создании вложенных состояний

---

src/renderer/src/components/PropertiesModal/PropertiesModal.tsx
src/renderer/src/lib/data/EditorModel/EditorModel.ts

close https://github.com/kruzhok-team/lapki-client/issues/600
close https://github.com/kruzhok-team/lapki-client/issues/601

Исправление окна редактирования свойств

---

src/renderer/src/components/Sidebar/Menu.tsx

close https://github.com/kruzhok-team/lapki-client/issues/602

Убрать возможность перейти в текстовый режим во вкладках не-редактора

---

src/renderer/src/components/Sidebar/Explorer/StateMachineComponentList.tsx
src/renderer/src/components/Sidebar/Explorer/StateMachinesHierarchy.tsx
src/renderer/src/lib/data/EditorModel/FilesManager.ts
src/renderer/src/lib/data/ModelController/CanvasController.ts
src/renderer/src/lib/data/ModelController/ComponentsController.ts
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/StateMachineController.ts

...а также убрал отображение "фантомной" МС в иерархии, если у нас открыта схема, но закрыты все вкладки

Фикс истории при создания состояния, фикс бага со статическими компонентами, отписка схемоэкрана от событий при создании новой схемы

---

src/renderer/src/components/Sidebar/Compiler.tsx
src/renderer/src/components/Sidebar/Loader.tsx

Кнопка "Прошить..." доступна при условии, если успешно скомпилировалась хотя бы одна машина состояний.
close #611

Кнопка "Прошить..." доступна даже если ни одна МС не выбрана

---

src/renderer/src/hooks/useFileOperations.ts

close https://github.com/kruzhok-team/lapki-client/issues/608

Фикс отмены импорта при отказе сохранить несохраненные изменения

---

src/renderer/src/components/SaveRemindModal.tsx
src/renderer/src/components/UI/Modal/Modal.tsx
src/renderer/src/index.css

Улучшение формы напоминания о сохранении файла

---

src/renderer/src/lib/data/EditorModel/EditorModel.ts

Переименование компонентов в атрибутах-параметрах перестало работать в одном из PR.

Переименование компонентов в атрибутах-параметрах (фикс)

---

src/renderer/src/components/Sidebar/Explorer/StateMachineComponentList.tsx

close https://github.com/kruzhok-team/lapki-client/issues/642

Фикс перетаскивания компонентов

---

src/renderer/src/lib/data/GraphmlParser.ts

close https://github.com/kruzhok-team/lapki-client/issues/640

Фикс загрузки нескольких атрибутов-параметров

---

src/renderer/src/lib/data/GraphmlBuilder.ts

Производилась попытка проверить undefined параметр на наличие полей

Фикс экспорта в CGML при использовании параметров по умолчанию

---

src/renderer/src/components/FirmwareSelectMS1.tsx
src/renderer/src/components/ManagerMS.tsx

- В окне выбора прошивок у всех машин состояний по-умолчанию стоит галочка.
- Удалена кнопка "Выбрать", кнопка закрытия формы переименована на "Вернуться". Теперь все изменения всегда фиксируются при закрытии формы.
- Отмеченная галочкой машина состояний без выбранного адреса не мешает закрытию формы, такая машина состояний просто не отправится в загрузчик.

Менеджер МС-ТЮК: прошивка по-умолчанию

---

src/main/settings.ts
src/renderer/src/components/ManagerMS.tsx
src/renderer/src/components/MsGetAddressModal.tsx

close https://github.com/kruzhok-team/lapki-client/issues/660
~~Потребуется сброс настроек.~~ (UPD: Сброс настроек не нужен)

Инструкция по получению адреса МС-ТЮК

---

src/renderer/src/lib/basic/EditorView.ts
src/renderer/src/lib/basic/Mouse.ts
src/renderer/src/lib/data/ModelController/StatesController.ts
src/renderer/src/lib/drawable/Shape.ts
src/renderer/src/lib/types/mouse.ts

close https://github.com/kruzhok-team/lapki-client/issues/656
close https://github.com/kruzhok-team/lapki-client/issues/390

Фикс передвижения состояния при переименовании через "карандаш"

---

src/renderer/src/components/Sidebar/Explorer/Explorer.tsx
src/renderer/src/components/Sidebar/Sidebar.tsx
src/renderer/src/store/useSidebar.ts

- Замена «Проводник» -> «Диаграмма»
- Замена «Структура» -> «Иерархия»
- Замена положений вкладок Машина состояний и Проводник (Диаграмма)

Правки в Sidebar

---

src/renderer/src/components/Sidebar/Menu.tsx
src/renderer/src/components/Sidebar/Sidebar.tsx

- подсказка про синий кружок в углу «Документ»-а
- дублирование кружка рядом с кнопкой «Сохранить»

Синие кружки и подсказки при несохранённом документе

---

src/renderer/src/index.css
src/renderer/src/lib/data/PlatformManager.tsx
src/renderer/src/lib/drawable/TransitionNode/Label.ts
src/renderer/src/theme.ts
tailwind.config.js

Новая палитра цветов для обоих тем. На скриншотах слева - старая тема, справа - новая.
Светлая тема:
Темная тема:

Новая палитра цветов

---

src/renderer/src/components/MainContainer/NotInitialized.tsx

- Удалена заливка
- Цвет обводки и текста зависит от темы

Изменение стиля горячих клавиш

---

src/renderer/src/components/NodeModal/EditEventModal.tsx
src/renderer/src/components/NodeModal/TransitionModal.tsx
src/renderer/src/components/NodeModal/components/Trigger.tsx
src/renderer/src/components/NodeModal/hooks/useTrigger.tsx

Выдает ошибку если:
- Используются повторно системные события
- Используются одинаковые триггеры и условия (если разные условия, то событие валидно)
close https://github.com/kruzhok-team/lapki-client/issues/560
close https://github.com/kruzhok-team/lapki-client/issues/559

Валидация событий в состояниях и переходах, создание события в состоянии без действий 

---

src/renderer/src/lib/constants.ts
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/StatesController.ts

Центрирование канваса после создания первого элемента, изменение расстояния от начального псевдосостояния

---

src/renderer/src/components/Sidebar/Labels.tsx
src/renderer/src/components/Sidebar/Sidebar.tsx

Выделение иконки документации

---

src/renderer/src/components/UI/Switch.tsx

Обводка для Switch

---

src/renderer/src/components/CreateSchemeModal/CreateSchemeModal.tsx
src/renderer/src/components/CreateSchemeModal/PlatformSelection.tsx
src/renderer/src/components/CreateSchemeModal/TemplateSelection.tsx
src/renderer/src/components/Hierarchy/TitleRender.tsx
src/renderer/src/components/NodeModal/StateModal.tsx
src/renderer/src/components/NodeModal/components/ColorField.tsx
src/renderer/src/components/NodeModal/components/Event.tsx
src/renderer/src/components/NodeModal/components/css/event.css
src/renderer/src/components/Sidebar/Explorer/StateMachineComponentList.tsx

Из того, что сходу обнаружилось по UX
Из возможного на будущее:

Улучшения по UX

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx

Когда пользователь делал двойной клик на событии, приложение вылетало

Фикс вылета при вызове окна редактирования конкретного события через редактор

---

src/renderer/src/components/Sidebar/Menu.tsx
src/renderer/src/lib/basic/EditorView.ts

CTRL+Z
CTRL+Y
CTRL+S
CTRL+SHIFT+S

Глобальные хоткеи

---

src/renderer/src/components/StateMachineNameEdit.tsx
src/renderer/src/hooks/useComponents.ts
src/renderer/src/lib/constants.ts
src/renderer/src/lib/data/GraphmlParser.ts
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/StatesController.ts
src/renderer/src/lib/drawable/Shape.ts
src/renderer/src/lib/drawable/StateMachineNode/StateMachine.ts
src/renderer/src/lib/drawable/StateNode/ChoiceState.ts
src/renderer/src/lib/drawable/StateNode/EdgeHandlers.ts
src/renderer/src/lib/drawable/StateNode/State.ts
src/renderer/src/lib/drawable/TransitionNode/ArrowsWithLabel.ts
src/renderer/src/lib/types/ControllerTypes.ts

close https://github.com/kruzhok-team/lapki-client/issues/652

Отрисовка дочерних элементов поверх родительского контейнера

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
src/renderer/src/components/NodeModal/components/Actions.tsx
src/renderer/src/components/NodeModal/components/Trigger.tsx
src/renderer/src/components/StateMachineEditModal.tsx

Улучшение UX модалок

---

src/renderer/src/components/MainContainer/MainContainer.tsx

close https://github.com/kruzhok-team/lapki-client/issues/758

Фикс сброса автосохранения

---

resources/platform/empty.json
src/renderer/src/lib/data/GraphmlParser.ts

Пустая платформа

---

.github/workflows/manual-release.yml
.github/workflows/tagged-release.yml
src/main/index.ts
src/main/modules/ModuleManager.ts

close https://github.com/kruzhok-team/lapki-client/issues/408
IDE не видел avrdude, если он добавлен в папку с загрузчиком

Фикс проверки наличия локального avrdude

---

src/renderer/src/components/Sidebar/Menu.tsx

Вкладка документ: переименование кнопок и выравнивание по левому краю

---

src/renderer/src/components/Sidebar/Flasher/Flasher.tsx
src/renderer/src/components/Sidebar/Flasher/SerialMonitor.tsx

close https://github.com/kruzhok-team/lapki-client/issues/777

Выделение текста в окнах с логами в Загрузчике и в Мониторе порта

---

src/renderer/src/hooks/useFlasherHooks.ts

close https://github.com/kruzhok-team/lapki-client/issues/782

Сброс выбранных прошивок при смене документа в таблице прошивок

---

src/main/settings.ts

Исправление бага из-за которого IDE не запускалось без наличия недавних файлов в настройках.

Фикс инициализации недавних файлов

---

src/renderer/src/components/Sidebar/Flasher/FlasherTable.tsx

Строгая проверка версии для матрицы и нестрогая проверка для всех остальных плат.

Смешанная проверка версий плат МС-ТЮК

---

src/renderer/src/components/Sidebar/Compiler.tsx

При нажатии на кнопку "Журнал компиляции" вкладка переоткрывается с новыми данными.

Обновление вкладки журнала компиляции

---

src/main/settings.ts
src/renderer/src/components/MainContainer/MainContainer.tsx
src/renderer/src/components/SaveRemindModal.tsx
src/renderer/src/hooks/useFileOperations.ts

close https://github.com/kruzhok-team/lapki-client/issues/815

Фикс бага с сохранением списка недавних файлов

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx

Старая проверка игнорировала компоненты, у которых нет методов, но есть переменные.

Фикс проверки атрибутов как параметров

---

src/renderer/src/components/Modules/ActualizeResponse.ts
src/renderer/src/components/Modules/DowngradeResponse.ts
src/renderer/src/components/Sidebar/Menu.tsx
src/renderer/src/types/CompilerTypes.ts

fix https://github.com/kruzhok-team/lapki-client/issues/799

Фикс экспорта в Берлогу, запрет на переход в текстовый режим для схем Берлоги

---

src/renderer/src/components/Documentation/Documentation.tsx

- Блокировка кнопки "Просмотр" при отсутствии выбранной страницы.
- Заглавие "Документация" и крестик для закрытия.

Улучшение UX документации

---

src/main/file-handlers/handlers.ts
src/renderer/src/components/Sidebar/History.tsx

Интерфейс
Сохранение истории идёт в json-файл ([пример](https://github.com/user-attachments/files/19119759/history-2.json))

Экспорт истории изменений

---

src/renderer/src/components/Sidebar/Flasher/Flasher.tsx

Предлагал установить avrdude для КиберМишки.

Фикс проверки на avrdude

---

src/renderer/src/components/Sidebar/Explorer/Explorer.tsx
src/renderer/src/components/Sidebar/Explorer/StateMachineComponentList.tsx
src/renderer/src/components/Sidebar/Explorer/StateMachinesHierarchy.tsx
src/renderer/src/components/Sidebar/StateMachinesTab/StateMachinesList.tsx

- Заголовки больше не прокручиваются
- Поиск в иерархии тоже не прокручивается

Исправление скролла на боковой панели Диаграмма

---

resources/platform/ArduinoMicro-1.0.json
resources/platform/ArduinoUno-1.0.json
resources/platform/tjc-ms1-btn-a2-1.0.json
resources/platform/tjc-ms1-lmp-a3-1.0.json
resources/platform/tjc-ms1-main-a4-1.0.json

- Перевод и описание метода isReleased для платформы "МС-ТЮК-1: Кнопочница"
- Исправление названия и использование псевдонима для значения LED

Исправление описаний платформ

---

src/renderer/src/lib/data/GraphmlBuilder.ts

close https://github.com/kruzhok-team/lapki-client/issues/895

Фикс сериализации пустых параметров компонента

---

src/renderer/src/lib/data/ModelController/CanvasController.ts
src/renderer/src/lib/data/ModelController/ModelController.ts

close https://github.com/kruzhok-team/lapki-client/issues/899

Фикс отсутствия сохранения метки при одновременном изменении метки и тех. названия

---

src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx

close https://github.com/kruzhok-team/lapki-client/issues/907

Фикс сохранения параметров после закрытия вкладки редактирования действия

---

src/renderer/src/lib/data/ModelController/UserInputValidator.ts

Исправление проверки совпадения технического имени с названиями классов компонентов

---

src/renderer/src/components/Modules/ManagerMS.ts
src/renderer/src/components/Modules/SerialMonitor.ts
src/renderer/src/components/PropertiesModal/PropertiesModal.tsx
src/renderer/src/utils/index.ts

Время сообщений в загрузчике и мониторе порта

---

src/renderer/src/components/DiagramEditor.tsx
src/renderer/src/components/NodeModal/ActionsModal/ActionsModal.tsx
src/renderer/src/components/NodeModal/components/Actions.tsx
src/renderer/src/components/NodeModal/hooks/useActions.tsx

close https://github.com/kruzhok-team/lapki-client/issues/906

Фикс одновременного изменения нескольких действий

---

src/renderer/src/hooks/useFileOperations.ts
src/renderer/src/hooks/useFlasherHooks.ts

Исправление сброса таблицы прошивок

---

src/main/settings.ts

Глубокая проверка electron-settings

---

src/renderer/src/components/ReferenceModal/ComponentInfo.tsx
src/renderer/src/components/ReferenceModal/ComponentReference.tsx
src/renderer/src/components/ReferenceModal/ReferenceModal.tsx
src/renderer/src/components/ReferenceModal/index.ts
src/renderer/src/components/Sidebar/Menu.tsx
src/renderer/src/lib/data/PlatformManager.tsx

Модалка, доступная из вкладки «Документ».

Справочник компонентов

---

src/renderer/src/components/Documentation/Documentation.tsx
src/renderer/src/components/ReferenceModal/ComponentInfo.tsx
src/renderer/src/components/ReferenceModal/ComponentReference.tsx
src/renderer/src/components/ReferenceModal/ComponentReferenceV.tsx
src/renderer/src/components/ReferenceModal/Reference.tsx
src/renderer/src/components/Sidebar/Menu.tsx
src/renderer/src/components/utils/html-element-to-react.ts

Справочник вынесен из главного меню в документацию.

Справочник компонентов: перенос в документацию

---

src/renderer/src/assets/icons/upload-file.svg
src/renderer/src/components/Sidebar/Flasher/FlasherTable.tsx

Загрузчик: иконка для кнопки выбора файла и подсказки

---

src/renderer/src/lib/data/EditorModel/EditorModel.ts
src/renderer/src/lib/data/ModelController/CanvasController.ts
src/renderer/src/lib/data/ModelController/ModelController.ts
src/renderer/src/lib/data/ModelController/StatesController.ts
src/renderer/src/lib/types/ControllerTypes.ts
src/renderer/src/types/diagram.ts

Когда мы выделяем событие/действие, то выделяется и состояние, поэтому в приоритете удаление действия, а затем самого состояния

Удаление выделенных событий/действий
